# Generated by Django 3.2.15 on 2024-12-09 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import web.helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roles', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('mapel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'MataPelajaran',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Murid',
            fields=[
                ('murid_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('jenis_kelamin', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=web.helper.RandomFileName('murid/foto/'))),
                ('tanggal_lahir', models.DateField()),
                ('status', models.BooleanField()),
                ('kelas', models.BigIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('ortu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.abstractuser')),
            ],
            options={
                'db_table': 'Murid',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransaksiPembayaran',
            fields=[
                ('transaksi_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bukti_pembayaran', models.ImageField(blank=True, null=True, upload_to=web.helper.RandomFileName('transaksi/bukti/'))),
                ('status', models.BooleanField()),
                ('jumlah', models.BigIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('murid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.murid')),
            ],
            options={
                'db_table': 'TransaksiPembayaran',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('berita_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nilai', models.BigIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('guru', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.abstractuser')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.matapelajaran')),
                ('murid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.murid')),
            ],
            options={
                'db_table': 'Nilai',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('komentar_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=web.helper.RandomFileName('forum/komentar/'))),
                ('komentar', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.abstractuser')),
            ],
            options={
                'db_table': 'Komentar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ForumDiskusi',
            fields=[
                ('forum_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=web.helper.RandomFileName('forum/foto/'))),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.abstractuser')),
            ],
            options={
                'db_table': 'ForumDiskusi',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('berita_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=web.helper.RandomFileName('berita/foto/'))),
                ('jenis', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.abstractuser')),
            ],
            options={
                'db_table': 'Berita',
                'managed': True,
            },
        ),
    ]
