# Generated by Django 3.2.15 on 2024-12-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksipembayaran',
            name='keterangan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
