# Generated by Django 4.2.21 on 2025-06-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transaksipembayaran_keterangan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nilai',
            old_name='berita_id',
            new_name='nilai_id',
        ),
    ]
